name: Bug Report
description: Report a problem on the platform
title: "[Bug]: "
labels: ["kind/bug", "status/needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: impacted_user_id
    attributes:
      label: Impact User's ID
      description: The ID of the impacted user
      placeholder: ex. 184
    validations:
      required: false
  - type: input
    id: impacted_user_email
    attributes:
      label: Impact User's email address
      description: The email address of the impacted user
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A description of the bug
      placeholder: Tell us what you happened!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: How is it expected to behave?
      placeholder: Tell us what shoudl have happened
      value:
    validations:
      required: false
  - type: textarea
    id: reproduction-steps
    attributes:
      label: How to reproduce
      description: Detailed steps to reproduce the bug
      value:
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: dropdown
    id: impacted-services
    attributes:
      label: What parts of the software are impacted?
      multiple: true
      options:
        - Search
        - Workflow
        - IRM
        - Inbox
